

def print_help():
    print("Below is the list of commands available to use:")
    print()
    print("help")
    print("\tShow this message.")
    print()
    print("exit / quit / q")
    print("\tExit the program.")
    print()
    print("update")
    print("\tForce update of entire database.")
    print("\tWARNING!!")
    print("\tThis requires internet connection and should take approximately 5-10 minutes.")
    print()
    print("search \"<Pokémon name>\" or search <Pokédex number")
    print("\tSearch for a Pokémon by name or Pokédex number.")
    print("\tWhile searching by name you can type prefix of the name.")
    print("\t\"search Pik\" will find both Pikachu and Pikipek.")
    print("\tBut \"search ori\" will find Oricorio, but won't find Nidorina, Nidorino, Chikorita, Anorith, Gothorita and Munkidori.")
    print("\tIf multiple matches are found you'll be asked to pick one and information about selected Pokémon will be shown.")
    print("\tPokémon name should be in quotation marks so that program can properly handle Pokémon whose name has whitespace like Taku Koko.")
    print()
    print("type <type name>")
    print("\tSearch for all Pokémon of the given type.")
    print("\tYou can search for multiple types - program will look for Pokémon that have all given types.")
    print("\t\"type fire\" will find all Pokémon with Fire type.")
    print("\t\"type fire water\" will find all Pokémon that have both Fire and Water type.")
    print()
    print("fight \"<Pokémon1 name>\" \"<Pokémon2 name>\" <level>*")
    print("\tSimple comparison between two Pokémon and simulate 1v1 fight between them.")
    print("\tThis is simple fight. More advanced factors like: IVs, EVs, natures, held items, weather, status moves etc. are not taken into account.")
    print("\tLearnset of Pokémon is not taken into account - power of moves used is an estimated median value.")
    print("\tYou can type level that should be set for these Pokémon. It's optional, if not given, program will assume level 50.")
    print("\tPokémon names should be in quotation marks so that program can properly handle Pokémon whose names have whitespace like Taku Koko.")
    print("\tExample: fight \"Taku Koko\" \"Victreebel\".")