from wrap_text import wrap_text

def print_help():
    print(wrap_text("Below is the list of commands available to use:"))
    print()
    print(wrap_text("help"))
    print(wrap_text("\tShow this message."))
    print()
    print(wrap_text("exit / quit / q"))
    print(wrap_text("\tExit the program."))
    print()
    print(wrap_text("update"))
    print(wrap_text("\tForce update of entire database."))
    print(wrap_text("\tWARNING!!"))
    print(wrap_text("\tThis requires internet connection and should take approximately 5-10 minutes."))
    print()
    print(wrap_text("search \"<Pokémon name>\" or search <Pokédex number>"))
    print(wrap_text("\tSearch for a Pokémon by name or Pokédex number."))
    print(wrap_text("\tWhile searching by name you can type prefix of the name."))
    print(wrap_text("\t\'search \"Pik\"\' will find both Pikachu and Pikipek."))
    print(wrap_text("\tBut \"search ori\" will find 4 forms of Oricorio, but won't find Nidorina, Nidorino, Chikorita, Anorith, Gothorita and Munkidori."))
    print(wrap_text("\tIf multiple matches are found you'll be asked to pick one and information about selected Pokémon will be shown."))
    print(wrap_text("\tPokémon name should be in quotation marks so that program can properly handle Pokémon whose name has whitespace like Tapu Koko."))
    print(wrap_text("\tQuotation marks are not needed if search term doesn't use whitespace."))
    print()
    print(wrap_text("type <type name>"))
    print(wrap_text("\tSearch for all Pokémon of the given type."))
    print(wrap_text("\tYou can search for multiple types - program will look for Pokémon that have all given types."))
    print(wrap_text("\t\"type fire\" will find all Pokémon with Fire type."))
    print(wrap_text("\t\"type fire water\" will find all Pokémon that have both Fire and Water type."))
    print(wrap_text("\t\At the time of writing this program, Pokémon have maximum of 2 different types. As a result searching for 3 types at the same time is not implemented."))
    print()
    print(wrap_text("fight \"<Pokémon1 name>\" \"<Pokémon2 name>\" <level>*"))
    print(wrap_text("\tSimple comparison between two Pokémon and simulate 1v1 fight between them."))
    print(wrap_text("\tThis is simple fight. More advanced factors like: IVs, EVs, natures, held items, weather, status moves etc. are not taken into account."))
    print(wrap_text("\tLearnset of Pokémon is not taken into account - power of moves used is an estimated median value."))
    print(wrap_text("\tYou can type level that should be set for these Pokémon. It's optional, if not given, program will assume level 50."))
    print(wrap_text("\tPokémon names should be in quotation marks so that program can properly handle Pokémon whose names have whitespace like Tapu Koko."))
    print(wrap_text("\tExample: fight \"Tapu Koko\" \"Victreebel\"."))